### PR TITLE
upgrade psycopg2 to >=2.7 to handle postgres >=10

### PR DESCRIPTION
**Pull request by AlexRiina**
psycopg2<2.7 looks for the a postgres version like x.xx which unfortunately crashes trying to match 10.xx see https://github.com/psycopg/psycopg2/issues/594

The version of psycopg2 isn't required if the postgres version is <10 but it seems like travis is using postgres 10.1 if there isn't a postgres version specified so I could remove the requirements.txt change.

### CODE REVIEW

**Comment by AlexRiina** [comment]
Here's a link to a travis run where this is crashing https://travis-ci.org/orcasgit/django-fernet-fields/jobs/467630010.

```
Collecting psycopg2==2.6
  Using cached https://files.pythonhosted.org/packages/dd/c7/9016ff8ff69da269b1848276eebfb264af5badf6b38caad805426771f04d/psycopg2-2.6.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: could not determine PostgreSQL version from '10.1'
```

**Comment by brad** [comment]
@AlexRiina Sorry I took so long, the tests on this PR are failing again due to bitrot. Do you have any interest in addressing them? Otherwise I will address them myself

**Comment by AlexRiina** [comment]
no worries. A few more versions of python / django fell out of long term support and a few new versions are available now (3.7 just got to travis), so I've made those changes at the same time as figuring out what was going wrong with postgres.

**Comment by brad** [comment]
Thanks @AlexRiina! And @MightySCollins for the :eyes:

**Comment by brad** [comment]
Released as 0.6

**Pull request merged**
